apiVersion: apps/v1
kind: Deployment
metadata:
  name: diary-svc
  namespace: default
  labels:
    app: diary-svc
spec:
  selector:
    matchLabels:
      app: diary-svc
  replicas: 1
  strategy:
  template:
    metadata:
      labels:
        app: diary-svc
    spec:
      containers:
      - name: diary-svc
        image: gcr.io/microsservices/diary-image:latest
        imagePullPolicy: Never
        env:
          - name: DB_URL
            value: "postgresql://postgres:postgres@postgres:5432/"
