// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgquery

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID        uuid.UUID
	PostOwner string
	Content   string
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID       uuid.UUID
	Username string
	Password string
}
