name: Build and test - on CI server

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TESTCONTAINER_DOCKER_NETWORK: tomodachi-testcontainers
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Setup Docker Network for Testcontainers
        run: docker network create ${{ env.TESTCONTAINER_DOCKER_NETWORK }}

      - name: Download Modules
        run: go mod download

      - name: Run tests
        working-directory: 
        run: go test -v ./tests