name: Build and test - on CI server

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TESTCONTAINER_DOCKER_NETWORK: tomodachi-testcontainers
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - name: Setup Docker Network for Testcontainers
        run: docker network create ${{ env.TESTCONTAINER_DOCKER_NETWORK }}

      - name: Test go version
        run: go version

      - name: Run tests
        working-directory: 
        run: go test -v ./tests