name: Build and test - on CI server

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TESTCONTAINER_DOCKER_NETWORK: tomodachi-testcontainers
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5

      - name: Create Docker network for running Testcontianers
        run: docker network create ${{ env.TESTCONTAINER_DOCKER_NETWORK }}

      - name: Test go version
        run: go version

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Build Docker image - Release
      #   uses: docker/build-push-action@v5
      #   with:
      #     target: release
      #     load: true